
# Spring Data JPA properties
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true